---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

# Verifies action/workflow calls are pinned to SHA commits
name: "📌 Check Actions/Workflows"

  # yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master
    paths: [".github/**"]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-actions:
    name: Check Actions/Workflows
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Scorecard Action
        uses: os-climate/osc-github-devops/.github/actions/ossf-scorecard-action@main
